apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-board-api
  labels:
    app: upload-board-api
    type: back-end

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: upload-board-api
        type: back-end
    spec:
      containers:
        - name: upload-board-api
          image: bluecode1775/sharenpo:latest
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: upload-board-api
