apiVersion: v1
kind: Service
metadata:
  name: upload-board-api-cluster-ip-service
spec:
  selector:
    app: upload-board-api
  type: ClusterIP
  ports:
    # Cluster Port
    - port: 3000
      # Container Port
      targetPort: 3000
