apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-board-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upload-board-api
  template:
    metadata:
      labels:
        app: upload-board-api
    spec:
      containers:
        - name: upload-board-api
          image: bluecode1775/sharenpo:latest
          ports:
            - containerPort: 3000
